# Generated by Django 5.0.6 on 2024-08-09 02:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hanabi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='duration',
        ),
        migrations.AddField(
            model_name='game',
            name='numplayers',
            field=models.PositiveSmallIntegerField(default=2, validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='deck',
            name='cards',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='gameplayer',
            name='hand',
            field=models.JSONField(null=True),
        ),
    ]
