# Generated by Django 5.0.6 on 2024-08-09 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hanabi', '0004_game_creator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='status',
            field=models.PositiveBigIntegerField(choices=[(1, 'New'), (2, 'In Progress'), (3, 'Finished')], default=1),
        ),
    ]
