# Generated by Django 5.0.6 on 2024-08-09 16:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hanabi', '0005_alter_game_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gameplayer',
            name='hand',
        ),
        migrations.AddField(
            model_name='gameplayer',
            name='turn_order',
            field=models.PositiveBigIntegerField(null=True),
        ),
        migrations.CreateModel(
            name='GameState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currentPlayer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('deck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hanabi.deck')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hanabi.game')),
            ],
        ),
    ]
