# Generated by Django 5.0.6 on 2024-08-09 20:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hanabi', '0006_remove_gameplayer_hand_gameplayer_turn_order_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamestate',
            name='deck',
        ),
        migrations.RemoveField(
            model_name='gamestate',
            name='currentPlayer',
        ),
        migrations.RemoveField(
            model_name='gamestate',
            name='game',
        ),
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cards', models.JSONField(null=True)),
                ('currentPlayer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hanabi.game')),
            ],
        ),
        migrations.DeleteModel(
            name='Deck',
        ),
        migrations.DeleteModel(
            name='GameState',
        ),
    ]
