# Generated by Django 5.0.6 on 2024-08-09 20:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hanabi', '0007_remove_gamestate_deck_remove_gamestate_currentplayer_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gameplayer',
            old_name='player',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='board',
            name='currentPlayer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
