# Generated by Django 5.0.6 on 2024-07-13 18:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_category_alter_listing_title_listing_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.ForeignKey(default='Other', on_delete=django.db.models.deletion.SET_DEFAULT, to='auctions.category'),
        ),
    ]
