# Generated by Django 5.0.6 on 2024-07-14 14:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_watchlistitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchlistitem',
            name='listing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watchlistlistings', to='auctions.listing'),
        ),
    ]
